# Generated by Django 3.2.15 on 2023-03-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=250)),
                ('answers', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pyschiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.login')),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.pyschiatrist')),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.CharField(max_length=250)),
                ('descriptions', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.pyschiatrist')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='chatbot.login')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='chatbot.login')),
            ],
        ),
    ]
