# Generated by Django 3.2.15 on 2023-04-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='answers',
        ),
        migrations.AddField(
            model_name='pyschiatrist',
            name='expireance',
            field=models.CharField(default=888, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pyschiatrist',
            name='image',
            field=models.FileField(default=66, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default=99, upload_to=''),
            preserve_default=False,
        ),
    ]
