# Generated by Django 3.2.15 on 2023-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20230408_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.BigIntegerField()),
                ('query', models.CharField(max_length=500)),
            ],
        ),
    ]
