# Generated by Django 3.2.15 on 2023-04-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_query_query_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
