# Generated by Django 3.2.15 on 2023-04-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='sentiments',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
